// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChannelList: typeof import('./src/components/nav/channel-list.vue')['default']
    Checkbox: typeof import('./src/components/inputs/checkbox.vue')['default']
    Coffee: typeof import('./src/components/nav/coffee.vue')['default']
    FileGallery: typeof import('./src/components/files/file-gallery.vue')['default']
    FilePreview: typeof import('./src/components/files/file-preview.vue')['default']
    Icon: typeof import('./src/components/nav/icon.vue')['default']
    LoadSplash: typeof import('./src/components/nav/load-splash.vue')['default']
    Message: typeof import('./src/components/messages/message.vue')['default']
    MessageFormatModal: typeof import('./src/components/messages/message-format-modal.vue')['default']
    MessagesList: typeof import('./src/components/messages/messages-list.vue')['default']
    Modal: typeof import('./src/components/nav/modal.vue')['default']
    ReactChip: typeof import('./src/components/messages/react-chip.vue')['default']
    RepliesButton: typeof import('./src/components/messages/replies-button.vue')['default']
    SidebarFooter: typeof import('./src/components/nav/sidebar-footer.vue')['default']
  }
}

export { }
